version: '3.7'
services:
  db:
    container_name: db
    command: --init-file /data/application/init.sql
    build:
      context: docker/db
      args:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db
  web:
    container_name: web
    depends_on:
      - db
    build:
      context: './docker/web'
    volumes:
      - ./:/var/www/takeaway
    ports:
      - 5050:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      backend:
        aliases:
          - web
  lt:
    build:
      context: './docker/localtunnel'
    command: "usr/local/bin/lt --port 80 --subdomain ivailotakeaway --local-host web"
    depends_on:
      - web
    restart: always
    networks:
      backend:
        aliases:
          - lt
networks:
  backend:
    name: backend-network
