version: '3.7'
services:
  web:
    build:
      context: './docker/web'
    volumes:
      - ./:/var/www/takeaway
    ports:
      - 5050:80
    container_name: web
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3306:3307
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Root123!
      - MYSQL_DATABASE=takeaway
