version: '3.7'
services:
  db:
    build:
      context: './docker/db'
    env_file:
      - .env
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db
  web:
    build:
      context: './docker/web'
    volumes:
      - ./:/var/www/takeaway
    ports:
      - 5050:80
    container_name: web
    networks:
      backend:
        aliases:
          - web
networks:
  backend:
    name: backend-network
